### PR TITLE
added signal.is for SMS

### PR DESCRIPTION
**Pull request by sdushantha**
Hey!

I was looking through the network packages for the app Airtime and noticed an endpoint which sends a sms. Thought you might find it useful :)

### CODE REVIEW

**Comment by dragos-olaru** [comment]
How did you get it? From the app? Did you use burp suite to intercept the request on your phone?

**Comment by dragos-olaru** [comment]
It's not sending any sms. And after 5 attempts it says too many attempts

**Comment by sdushantha** [comment]
@dragos-olaru I was able to root my old Android phone today and then I used an Android app called HTTPCanary to intercept the traffic being sent by Airtime. Yes, you can monitor a single app using HTTPCanary if you wish. I am not 100% sure if doing this needs root. Just keep in mind that it's not possible to intercept the requests for all apps because some apps such as Snapchat use SSL pinning which prevents us from intercepting the traffic.

@LimerBoy Quick question, the site I added requires a POST request, but I dont see anywhere in the code or the services.json that specifies if the request requires a POST request or a GET request. Does this mean that all the services are using POST?

**Comment by dragos-olaru** [comment]
I am new to this things and i learned how to get the API from websites but i don't know what GET and POST do, but if you just put the website and the payload or data (that thing 'phone': '%phone' and the rest) it should work.

**Comment by sdushantha** [comment]
> It's not sending any sms. And after 5 attempts it says too many attempts

You are correct. From taking a look at the response text, it does give a `nextValidRequestDate`. 
```
{"code":"RateLimited","nextValidRequestDate":"2020-07-23T20:30:57.187Z"}
```

I'm currently not sure if we should add signal.is if it is very sensitive to multiple requests.

**Comment by LimerBoy** [comment]
> 
> @LimerBoy Quick question, the site I added requires a POST request, but I dont see anywhere in the code or the services.json that specifies if the request requires a POST request or a GET request. Does this mean that all the services are using POST?

Here is POST and GET request:
image

**Comment by dragos-olaru** [comment]
Post contains "data"

**Comment by sdushantha** [comment]
@LimerBoy Oh of course! POST requests use data while GET uses parameters. Sorry about that :/

**Comment by sdushantha** [comment]
Should this PR be closed since it is unsure if signal.is is going to work in the long run?

**Comment by dragos-olaru** [comment]
It's not going to work. I don't think the data is  'phone':'%phone%', and i don't think you can get the data from an android app(i will try later), so you can close this.

**Pull request closed without merging**
